### ISSUE TITLE
The start screen is unnecessary

### ISSUE THREAD

**Issue by Kwpolska** [upendra-k14/pip_gui#12]
It would be easier to put both installing, upgrading and uninstalling in one window, which will also get rid of the start screen.

**Comment by upendra-k14** [comment]
Sorry for replying late. I am open to discussion on this issue. I have made a start screen because we want to segregate these utilities in two parts as in coming days I want to add further functionalities such as installing from Pythonlibs which can be helpful for beginners. Further options like freezing the current state of installed pip packages and generating the requirement file needs to be added. 

Therefore, if we put all options in one sidebar it will be difficult for user to find correct options.
